- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install package to allow apt to use a repository over https
  apt:
      force_apt_get: yes
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: install Docker
  apt:
      name: docker-ce
      cache_valid_time: 86400

- name: Create new user
  user:
      name: streetstorm
      shell: /bin/bash
      groups:
        - sudo
        - docker
        
- name: add ssh key
  authorized_key:
      user: streetstorm
      key: https://github.com/streetstorm.keys
